language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - pip install -r requirements-test.txt
  - python setup.py install
script:
  - python setup.py test
notifications:
  irc: "irc.freenode.org#pyroutes"
